name: Echo Workflow

on:
  push:
    branches:
      - main

jobs:
  echo_messages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print start message
        run: echo "Starting the workflow..."

      - name: Print build message
        run: echo "Building the project..."

      - name: Print test message
        run: echo "Running tests..."

      - name: Print deploy message
        run: echo "Deploying the project..."

      - name: Print finish message
        run: echo "Workflow completed successfully!"



  
